modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="comfycoffin"
version="1.0.0"
displayName="ComfyCoffin"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="chivas, MCreator"

[[dependencies.comfycoffin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



